# Generated by Django 3.2.4 on 2021-08-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_age',
        ),
        migrations.AddField(
            model_name='student',
            name='stu_DOB',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_room',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_contact',
            field=models.CharField(default='', max_length=10),
        ),
    ]
