# Generated by Django 3.2.4 on 2021-08-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210806_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_DOB',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_room',
        ),
    ]
