# Generated by Django 3.2.4 on 2021-08-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210810_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_DOB',
            field=models.CharField(default='', max_length=10),
        ),
    ]
