# Generated by Django 3.2.4 on 2021-08-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_stu_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stu_DOB',
            new_name='stu_Day',
        ),
        migrations.AddField(
            model_name='student',
            name='stu_Month',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_Year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
