# Generated by Django 3.2.4 on 2021-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_stu_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_Mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
