# Generated by Django 3.2.4 on 2021-08-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_stu_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stu_Mobile',
            new_name='stu_contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_email',
        ),
    ]
