# Generated by Django 3.2.4 on 2021-08-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_stu_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_gender',
            field=models.CharField(default='', max_length=6),
        ),
    ]
