# Generated by Django 3.2.4 on 2021-08-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_stu_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='COURSES',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='City',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='Country',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='Pin_Code',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='State',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_branch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_room',
            field=models.CharField(default='', max_length=6),
        ),
    ]
