# Generated by Django 3.2.4 on 2021-11-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20210811_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='About_me_mail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='About_me_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='About_me_text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
