# Generated by Django 3.2.4 on 2021-11-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20211109_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_me_name', models.CharField(max_length=20, null=True)),
                ('About_me_mail', models.CharField(max_length=50, null=True)),
                ('About_me_text', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='About_me_mail',
        ),
        migrations.RemoveField(
            model_name='student',
            name='About_me_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='About_me_text',
        ),
    ]
